### PR TITLE
fixed mlflow import error

### PR DESCRIPTION
**Pull request by fengwang**

### CODE REVIEW

**Comment by Toumash** [comment]
The first commit makes sense. 

On what environment the the import error happens? What python and library version

**Comment by fengwang** [comment]
@Toumash I am using Python 3.10. My OS is ArchLinux. And the mlflow package is installed from https://aur.archlinux.org/packages/python-mlflow

**Comment by fengwang** [comment]
I am so sorry. Please ignore the readme part, and I am not intended to redirect users to my fork.

**Comment by Toumash** [comment]
I've updated the test script - it works now. Closing. Thank you!

**Pull request closed without merging**
